# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

setDebug <- function(debug_lvl) {
    invisible(.Call('_STASNet_setDebug', PACKAGE = 'STASNet', debug_lvl))
}

