# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

setDebug <- function(debug_lvl) {
    invisible(.Call('fitmodel_setDebug', PACKAGE = 'fitmodel', debug_lvl))
}

